{% set name = "gpu-slic" %}
{% set version = "0.0.1a1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gpu_slic-{{ version }}.tar.gz
  sha256: e9a98283b493f422181c6fdb2d7ca843b3c90216faa526fbbe36f9b025c89375

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cupy >=7.0.0
    - jinja2
    - numpy
    - python >=3.6
    - scikit-image

test:
  imports:
    - cuda_slic
    - cuda_slic.slic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.stfc.ac.uk/RosalindFranklinInstitute/cuda-slic
  summary: CUDA implementation of the SLIC segmentaion algorithm.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - abonawas
