image: continuumio/miniconda3

test:
  tags:
    - gpu
  script:
    - apt-get update
    - apt-get install -y g++ gcc
    - conda update conda
    - conda install -y conda-build
    - conda env create -n gitlab-env -f environment.yml
    - conda activate gitlab-env
    - ./make_script.sh
    - python -m pytest tests-unit
    - nvidia-smi
    - nvcc --version
