# image: continuumio/miniconda3
image: condaforge/linux-anvil-cuda:10.2

before_script:
  - sudo yum install -y gcc gcc-c++  # these are pycuda depenencies
  - conda init bash
  - source /home/conda/.bashrc  # activate base miniconda environment

style-check:
  tags:
    - gpu
  script:
    - pip install black
    - pip install isort
    - isort --diff --check .
    - black --diff --check .

nvidia-debug:
  tags:
    - gpu
  script:
    - nvcc --version
    - nvidia-smi

tox:
  tags:
    - gpu
  script:
    - pip install tox
    - tox

unit-tests:
  tags:
    - gpu
  script:
    - conda env create -f environment.yml -v
    - conda activate cuda-slic
    - pip install pytest
    - pytest # test with pycuda
    - pip uninstall pycuda
    - pytest # test with cupy

memory-check:
  tags:
    - gpu
  script:
    - conda env create -f environment.yml -v
    - conda activate cuda-slic
    - pip install pytest
    - export PYCUDA_DEFAULT_NVCC_FLAGS="-lineinfo"
    - cuda-memcheck -- pytest

benchmark:
  tags:
    - gpu
  script:
    - conda env create -f environment.yml -v
    - conda activate cuda-slic
    - conda install ipython
    - python -m perf_analysis.compare_slic
    - ipython perf_analysis/throughput.ipy
    - pip uninstall pycuda # lets benchmark cupy code too
    - python -m perf_analysis.compare_slic
    - ipython perf_analysis/throughput.ipy
