# image: continuumio/miniconda3
image: condaforge/linux-anvil-cuda:10.1

before_script:
  - sudo yum install -y g++ gcc
  - conda init bash
  - source /home/conda/.bashrc
  - conda env create -f gitlab-ci-environment.yml -v
  - conda activate gitlab-ci
  - python survos2/improc/setup.py build_ext -i

test-nvidia-compilirs:
  tags:
    - gpu
  script:
    - nvcc --version

test-nvidia-smi:
  tags:
    - gpu
  script:
    - nvidia-smi

unit-tests:
  tags:
    - gpu
  script:
    - pytest
