# image: continuumio/miniconda3
image: condaforge/linux-anvil-cuda:10.1

before_script:
  - sudo yum install -y gcc gcc-c++  # these are pycuda depenencies
  - conda init bash
  - source /home/conda/.bashrc  # activate base miniconda environment

style-check:
  script:
    - pip install black
    # matching the version available at dls
    - pip install -Iv isort==4.3.21 
    - isort --recursive --check-only .
    - black --diff --check .

nvidia-debug:
  tags:
    - gpu
  script:
    - nvcc --version
    - nvidia-smi

tox:
  tags:
    - gpu
  script:
    - pip install tox
    - tox

unit-tests:
  tags:
    - gpu
  script:
    - conda env create -f gitlab-ci-environment.yml -v
    - conda activate gitlab-ci
    - pip install -e .
    - pytest

benchmark:
  tags:
    - gpu
  script:
    - conda env create -f gitlab-ci-environment.yml -v
    - conda activate gitlab-ci
    - pip install -e .
    - python -m perf_analysis.compare_slic
    - ipython perf_analysis/throughput.ipy