# image: continuumio/miniconda3
image: condaforge/linux-anvil-cuda:10.1

before_script:
  # - sudo yum install -y gcc gcc-c++  # these are pycuda depenencies
  - conda init bash
  # - source /root/.bashrc  # activate base miniconda environment
  - source /home/conda/.bashrc  # activate base miniconda environment

style-check:
  tags:
    - gpu
  script:
    - pip install black
    - pip install isort
    - isort --diff --check .
    - black --diff --check .

nvidia-debug:
  tags:
    - gpu
  script:
    - nvcc --version
    - nvidia-smi

tox:
  tags:
    - gpu
  script:
    - export CFLAGS="-I/usr/local/cuda/include"
    - export CUDA_PATH=/usr/local/cuda
    - export LD_LIBRARY_PATH=$CUDA_PATH/lib64:$LD_LIBRARY_PATH
    
    - pip install tox
    - tox

unit-tests:
  tags:
    - gpu
  script:
    - conda env create -f environment-cupy.yml -v
    - conda activate cupy-slic
    - pytest

benchmark:
  tags:
    - gpu
  script:
    - conda env create -f environment-cupy.yml -v
    - conda activate cupy-slic
    - python -m perf_analysis.compare_slic
    - ipython perf_analysis/throughput.ipy