# image: continuumio/miniconda3
image: condaforge/linux-anvil-cuda

before_script:
  - yum install -y g++ gcc
  - conda init bash
  - source /root/.bashrc
  - conda env create -f -v gitlab-ci-environment.yml
  - conda activate gitlab-ci
  - python survos2/improc/setup.py build_ext -i

test-nvidia-compilirs:
  tags:
    - gpu
  script:
    - nvcc --version

test-nvidia-smi:
  tags:
    - gpu
  script:
    - nvidia-smi

unit-tests:
  tags:
    - gpu
  script:
    - pytest
