# image: continuumio/miniconda3
image: condaforge/linux-anvil-cuda:10.1

before_script:
  # - sudo yum install -y gcc gcc-c++  # these are pycuda depenencies
  - conda init bash
  # - source /root/.bashrc  # activate base miniconda environment
  - source /home/conda/.bashrc  # activate base miniconda environment

style-check:
  tags:
    - gpu
  script:
    - pip install black
    - pip install isort
    - isort --diff --check .
    - black --diff --check .

nvidia-debug:
  tags:
    - gpu
  script:
    - nvcc --version
    - nvidia-smi

tox:
  tags:
    - gpu
  script:
    - sudo yum install centos-release-scl -y
    - sudo yum install devtoolset-7-gcc-c++ -y
    - source /opt/rh/devtoolset-7/enable
    - export NVCC="nvcc --compiler-bidir gcc-7"
    - pip install tox
    - tox

unit-tests:
  tags:
    - gpu
  script:
    - conda env create -f environment-cupy.yml -v
    - conda activate cupy-slic
    - pytest

benchmark:
  tags:
    - gpu
  script:
    - conda env create -f environment-cupy.yml -v
    - conda activate cupy-slic
    - python -m perf_analysis.compare_slic
    - ipython perf_analysis/throughput.ipy