# image: continuumio/miniconda3
image: condaforge/linux-anvil-cuda:10.1

before_script:
  - sudo yum install -y gcc gcc-c++
  - conda init bash
  - source /home/conda/.bashrc
  - conda env create -f gitlab-ci-environment.yml -v
  - conda activate gitlab-ci

test-nvidia-compilirs:
  tags:
    - gpu
  script:
    - nvcc --version

test-nvidia-smi:
  tags:
    - gpu
  script:
    - nvidia-smi

unit-tests:
  tags:
    - gpu
  script:
    - python survos2/improc/setup.py build_ext -i
    - pytest
