name: cuda-slic
channels:
- conda-forge
- default

dependencies:
- python=3.7
- pip
- numpy
- scikit-image
# test requirements
- pytest
- ipython
#notebook requirements
- notebook
- jupyter
- ipywidgets

- pip:
  - pycuda==2019.1.2
