name: cuda-slic
channels:
- conda-forge
- default

dependencies:
- python=3.7
- pip
- numpy
- scikit-image
- jinja2
# test requirements
- pytest
- ipython
# linting requirements
- flake8
- black
- isort
# notebook requirements
- notebook
- jupyter
- ipywidgets

- pip:
  - pycuda==2019.1.2
  # test requirements
  - -e .
