name: cuda-slic
channels:
- conda-forge
- default

dependencies:
- python=3.7
- pip
- numpy
- scikit-image
- jinja2
- cupy=7.8.0
- cudatoolkit=10.2

- pip:
  # gcc and g++/gcc-c++ are a requirement for pip installing pycuda on Linux
  # as well as cuda.h must be on include path. On Windows you need MSVC++ compiler
  # and C++ build tools
  - pycuda==2019.1.2
  # test requirements
  - -e .
