name: gpu-slic
channels:
- conda-forge
- default

dependencies:
- python=3.7
- pip
- cudatoolkit=10.1
- cudatoolkit-dev=10.1
- numpy
- h5py
- cython
- pytools
- pytest
- pywget
- hug
- pyyaml
- mrcfile
- dask
- matplotlib
- scikit-image
- tensorly
- pytest
- pip:
  - pycuda
