name: cupy-slic
channels:
- conda-forge
- default

dependencies:
- python=3.7
- pip
- numpy
- scikit-image
- jinja2

# # test requirements
# - twine
- pytest
- ipython
- tox
# # linting requirements
# - flake8
# - black
# - isort
# # notebook requirements
- notebook
- jupyter
- ipywidgets

- pip:
  # test requirements
  - cupy-cuda101
  - -e .
